**Introduction to Numpy**

Numpy (short for Numerical Python) provides an efficiente interface to store and operate on dense data buffers.

In [2]:
#Importing Library

import numpy as np

**Creating arrays**

From Lists

In [3]:
#Integer array

v1 = np.array([1,2,3,5])

type(v1)

numpy.ndarray

In [4]:
np.array([range(i,i+3) for i in [2,4,5]])

array([[2, 3, 4],
       [4, 5, 6],
       [5, 6, 7]])

Creating arrays from scracth

In [5]:
#Create a leng -10 integer array fillder with zeros

array_ceros = np.zeros(10, dtype=float)
print(array_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
#Create a 3x5 floatting -point array fillder with 1s
array_ones = np.ones((3,5), dtype=int)
print(array_ones)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [7]:
#Create a 3x5 array filled with 3.14
array_same_numbers = np.full((3,5),3.14)
array_same_numbers

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])