**Introduction to Numpy**

Numpy (short for Numerical Python) provides an efficiente interface to store and operate on dense data buffers.

In [2]:
#Importing Library

import numpy as np

**Creating arrays**

From Lists

In [3]:
#Integer array

v1 = np.array([1,2,3,5])

type(v1)

numpy.ndarray

In [4]:
np.array([range(i,i+3) for i in [2,4,5]])

array([[2, 3, 4],
       [4, 5, 6],
       [5, 6, 7]])

Creating arrays from scracth

In [5]:
#Create a leng -10 integer array fillder with zeros

array_ceros = np.zeros(10, dtype=float)
print(array_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
#Create a 3x5 floatting -point array fillder with 1s
array_ones = np.ones((3,5), dtype=int)
print(array_ones)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [7]:
#Create a 3x5 array filled with 3.14
array_same_numbers = np.full((3,5),3.14)
array_same_numbers

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [10]:
#Create an array filled with a linear sequence
#Starting  at 0 ending at 20, stteping by 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
#Create an array of five values eventlu spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
#Create 3x3 array of uniformly distribuited 
#random values between 0 and 1
np.random.random((3,3))

array([[0.98898309, 0.64169097, 0.42054584],
       [0.66009151, 0.39316502, 0.41748449],
       [0.20709774, 0.47657554, 0.24320153]])

In [17]:
#Create 3x3 array of normal distribuited 
#with mean 0 and standard deviation 1

np.random.normal(0,1,(3,3))

array([[-1.31149479, -1.54035807, -1.0852966 ],
       [-0.65540047, -1.10185972,  1.20848991],
       [-0.19914476,  0.21239547, -0.63591488]])

In [18]:
# Create a 3x3 array of random integers in the interval [0,10)
np.random.randint(0,10,(3,3))

array([[2, 5, 0],
       [5, 3, 3],
       [1, 9, 4]])

In [19]:
#Create a 3x3 identity matruix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Numpy Standard Data Types

Numpy arrays contain values of a single type, so it is important to have detailed knowledge of those type and ther limitations.
More information in https://numpy.org/doc/stable/user/basics.types.html

The Basics of Numpy Arrays

Attributes of Arrays:
Determing the size, shape, memory consumption, and data types of arrays

Indexing of arrays
Getting and setting the value of individual array elements

Slicing of arrays
Getting and setting smaller subarrays within a larger array

Reshaping of Arrays
Combining multiple arrays into one, and splitting one array into many

Numpy Array attributes

In [20]:
#Defining 3 randoms arrays: 1 upt to 3 dimensional arrays 
np.random.seed(0)

x1 = np.random.randint(10,size=6) #one dimensional array
x2= np.random.randint(10,size=(3,4)) #Two dimensional array
x3 = np.random.randint(10, size=(3,4,5)) # Three dimensioanl array

In [25]:
print(x1)

[5 0 3 3 7 9]


In [26]:
print(x2)



[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [27]:
print(x3)

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [21]:
#Dimension
print("X1 ndim: ", x1.ndim)
print("X2 ndim: ", x2.ndim)
print("X3 ndim: ", x3.ndim)



X1 ndim:  1
X2 ndim:  2
X3 ndim:  3


In [22]:
#Shape
print("X1 shape: ", x1.shape)
print("X2 shape: ", x2.shape)
print("X3 shape: ", x3.shape)


X1 shape:  (6,)
X2 shape:  (3, 4)
X3 shape:  (3, 4, 5)


In [28]:
#Size
print("X1 size: ", x1.size)
print("X2 size: ", x2.size)
print("X3 size: ", x3.size)



X1 size:  6
X2 size:  12
X3 size:  60


In [29]:
#Other way
print("Dtype: ", x1.dtype)

Dtype:  int32


Array Indenxing: Accesing Single Elements

In [30]:
x1

array([5, 0, 3, 3, 7, 9])

In [31]:
x1[0] #Python starts from 0

5

In [32]:
x1[4]

7

In [33]:
x1[-1]

9

In [34]:
x1[-2]

7

In [35]:
#In a multidimensional array, you access items using a comma-separated tuple of indices
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [36]:
x2[0,0]

3

In [37]:
x2[1,1]

6

Array Slicing: Accesing subarrays

Just we use square brackets to accesss subarrats with the slice notation, market by the colon : character. the Numpy slicing syntax is like this:
x[start:stop:step]

In [38]:
#one dimensional array
x1[:5] #from the beggining until element 5 or first five elements

array([5, 0, 3, 3, 7])

In [40]:
x1[5:] #Elements after index 5

array([9])

In [41]:
x1[::2] #Every other element. Each 2 

array([5, 3, 7])

In [42]:
x1[1::2] #every other element starting at index 1 

array([0, 3, 9])

Using negatives index the defaults for start and stop are swapped. 

In [43]:
x1[::-1] #all elements reversed

array([9, 7, 3, 3, 0, 5])

In [44]:
x1[5::-2] #reversed every other from index 5

array([9, 3, 0])

Multidimensional Subarrays

Multidimensioanl slices work in the same way, with multiple slices separated by comas.

In [47]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [46]:
x2[:2,:3] # Two rows, three columns

array([[3, 5, 2],
       [7, 6, 8]])

In [48]:
x2[:3,::2] #All rows, every other column

array([[3, 2],
       [7, 8],
       [1, 7]])

Accesing Array rows and columns
One commonly needed routine is accesing single rows or columns of an array. You can do this by combining indexing and slicing using an empty sliced marked by a single colon (:)

In [50]:
print(x2[:,0]) #first column of x2

[3 7 1]


In [51]:
print(x2[:,1])

[5 6 6]
